### ISSUE TITLE
Issue running on M1 arm

### ISSUE THREAD

**Issue by snuderl** [faust-streaming/cChardet#21]
### OS/Arch

```bash
$ python -c 'import platform;print(platform.uname())'
uname_result(system='Darwin', node='XMGFXH9WQL', release='22.3.0', version='Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000', machine='arm64')
```

### Python version

```bash
$ python --version
Python 3.10.3
```

### cChardet version

```bash
$ python -c 'import cchardet;print(cchardet.__version__)'
ImportError: dlopen(/Users/snuderl/.pyenv/versions/opensea/lib/python3.10/site-packages/cchardet/_cchardet.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_uchardet_data_end'
```

`faust_cchardet-2.1.16-cp310-cp310-macosx_11_0_arm64.whl
`
### What is the problem?

When trying to import cchardet get the following error. Works on 311 on same machine.

`ImportError: dlopen(/Users/snuderl/.pyenv/versions/opensea/lib/python3.10/site-packages/cchardet/_cchardet.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_uchardet_data_end'`

**Comment by wbarnha** [comment]
Unfortunately this project does not support M1 ARM for macOS yet. I'm waiting for the GitHub runners to add support. I need to yank the wheels for M1 from PyPi.

**Comment by wbarnha** [comment]
Closing since this is a duplicate.
